defaults:
- base_model

_target_: src.models.NeuralPosteriorEstimator
transforms: 4
d_model: [64, 64]
flow_type: MAF
embedding:
  _target_: src.models.embedding.TransformerEmbedding
  _partial_: True
  d_model: 8
