defaults:
  - data: ppi # win
  - model: npe # mde
  - trainer: default
  - _self_

task: estimation # criticism

log: True

c2st:
  check: True
  tol: 0.1

callbacks:
  stop_early: True
  patience: 20

hydra:
  job:
    chdir: True


# debugging settings
data:
  dataset:
    n_sample: 200
    load_data: False
trainer:
  fast_dev_run: True
