defaults:
  - _self_
  - data: sir
  - model: mde
  - trainer: debugging

task: criticism

log: True

c2st:
  check: True
  tol: 0.1

callbacks:
  stop_early: True
  patience: 20

hydra:
  job:
    chdir: True
